apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows all pods in the "dind" namespace to use the unrestricted PSP.
kind: ClusterRoleBinding
metadata:
  name: {{ include "secureremotedind.fullname" . }}-psp
roleRef:
  kind: ClusterRole
  name: secure-remote-dind-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "secureremotedind.serviceAccountName" . }} # name of your service account
  namespace: {{ .Release.Namespace }} # this is the namespace your service account is in