---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secure-remote-dind-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - secure-remote-dind-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use