---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secureremotedind.fullname" . }}-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - {{ include "secureremotedind.fullname" . }}-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use