{{- if .Values.serviceAccount.create -}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secureremotedind.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- include "secureremotedind.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end }}
