---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secureremotedind.fullname" . }}
  labels:
    {{- include "secureremotedind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dind-tls
      protocol: TCP
      name: dind-tls
  selector:
    {{- include "secureremotedind.selectorLabels" . | nindent 4 }}
