name: Helm-Release

on:
  push:
    branches:
      - main

## REF: https://faun.pub/semantic-version-of-helm-charts-in-github-actions-using-conventional-commits-ce5e0a587ce8
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code                   # Checkout source code
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Get specific changed files                  # To check if any files changed in charts/secure-remote-dind directory
        id: changed-files-specific
        uses: tj-actions/changed-files@v14.5
        with:
          since_last_remote_commit: true
          files: |
            Charts/secure-remote-dind/*

      - name: Automated Version Bump                      # Bump version in package.json
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR:  'Charts/secure-remote-dind'
        with:
          skip-tag:  'true'
          commit-message: 'CI: Bump Helm chart version to {{version}}'

      - name: update Chart.yaml                              # Update chart.yaml with new version and other fields
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        working-directory: Charts/secure-remote-dind
        run: |
          sed -i'.oldVersion' -e "/^version:/s;[^ ]*$;${{ steps.version-bump.outputs.newTag }};" Chart.yaml
          sed -i'.oldAppVersion' -e "/^appVersion:/s;[^ ]*$;${{ steps.version-bump.outputs.newTag }};" Chart.yaml

      - name: commit the new Chart.yml                   # commit the new Chart.yaml to main branch
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"